### PR TITLE
Linear and Mux caches implemented 

### PR DESCRIPTION
**Pull request by s-matyukevich**
This is a continuation of https://github.com/alecholmez/go-control-plane/pull/2 I decided to make a new PR in case we want to merge this separately. 

I reused the same [respondDelta](https://github.com/alecholmez/go-control-plane/commit/bf414ed5df63406b3bc91f60d2d9b259e71b3074#diff-328e7d10b4e4c71b0fb6e8104274aee8599b9955c6a53b30d1be06f4439b9d1bR23) method for both linear and snapshot caches, so the resulting implementation ends up being more or less straightforward.

### CODE REVIEW

**Comment by alecholmez** [comment]
I just merged your previous PR, I'll begin a review on these shortly. Thanks for all the contributions!

**Comment by alecholmez** [comment]
Just some initial thoughts:

- Can you add some unit tests for the delta mux/linear caching systems? I would be okay with just some small additions to the pre-existing unit tests in the respective folders
- IMO I'm not a huge fan of `delta_common.go`. It makes sense but I was thinking maybe now could potentially be a good time to organize some of the code? Potentially a folder structure like `pkg -> cache -> v2 -> delta / simple / mux / linear` that way there's some better organization of code as well as logical grouping of functionality? Then we can remove files like `delta_common` which doesn't seem too idiomatic. if you'd rather not do that in this PR I can make that change in my fork. Just curious on your thoughts about this

**Comment by alecholmez** [comment]
Also quick note make sure you sign your commits with DCO! `git commit -s -m "your message here"`

**Comment by s-matyukevich** [comment]
> Can you add some unit tests for the delta mux/linear caching systems? I would be okay with just some small additions to the pre-existing unit tests in the respective folders

Yes, I was going to add some unit tests. Will do this later.

> IMO I'm not a huge fan of delta_common.go. It makes sense but I was thinking maybe now could potentially be a good time to organize some of the code? Potentially a folder structure like pkg -> cache -> v2 -> delta / simple / mux / linear that way there's some better organization of code as well as logical grouping of functionality? Then we can remove files like delta_common which doesn't seem too idiomatic. if you'd rather not do that in this PR I can make that change in my fork. Just curious on your thoughts about this

Am I right that you are going to put in `delta` package only functionality that is shared between different caches? I guess  `CreateDeltaWatch` function must be defined in the same package where the struct itself is defined (in `linear`, `mux`, or `simple` packages) This is actually fine with me, my only concern is that delta functionality will be spread across different packages and some people may found it confusing, given the fact that we are going to have a dedicated `delta` package.

**Comment by alecholmez** [comment]
> > Can you add some unit tests for the delta mux/linear caching systems? I would be okay with just some small additions to the pre-existing unit tests in the respective folders
> 
> Yes, I was going to add some unit tests. Will do this later.
> 
> > IMO I'm not a huge fan of delta_common.go. It makes sense but I was thinking maybe now could potentially be a good time to organize some of the code? Potentially a folder structure like pkg -> cache -> v2 -> delta / simple / mux / linear that way there's some better organization of code as well as logical grouping of functionality? Then we can remove files like delta_common which doesn't seem too idiomatic. if you'd rather not do that in this PR I can make that change in my fork. Just curious on your thoughts about this
> 
> Am I right that you are going to put in `delta` package only functionality that is shared between different caches? I guess `CreateDeltaWatch` function must be defined in the same package where the struct itself is defined (in `linear`, `mux`, or `simple` packages) This is actually fine with me, my only concern is that delta functionality will be spread across different packages and some people may found it confusing, given the fact that we are going to have a dedicated `delta` package.

Correct that was what I had in mind for this. Yup code duplication will occur when we have to stub out the structs for each cache type but that's inevitable.

**Comment by alecholmez** [comment]
Awesome thank you for the tests! Merging

**Pull request merged**
